title: Pete Stewart
logo: "/images/profile.jpg?raw=True"
description: >
  Technology professional with 20 years of experience in data analytics, business management, and IT systems development.
  <br><br>
  Educational background in law and politics, data analytics and cybersecurity, with a BA in Political Science and an MS in Data Science with a Cybersecurity focus area.
  <br><br>
  <a href="https://www.linkedin.com/in/pvstewart/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-JDQ0RKSFTR # your Google Analytics tracking ID here
